name: Electron app PREMIUM

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-premium'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: setUpdaterChannel premium
        run: |
          node setUpdaterChannel premium
      - name: adjustPackageJsonPremium
        run: |
          node adjustPackageJsonPremium
      - name: yarn install
        run: |
          yarn install
      - name: Publish
        run: |
          yarn dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          # WIN_CSC_LINK: ${{ secrets.WINCERT_2025 }}
          # WIN_CSC_KEY_PASSWORD: ${{ secrets.WINCERT_2025_PASSWORD }}


      - name: Copy artifacts
        run: |
          mkdir artifacts          

          mv dist/*.exe artifacts/ || true
          mv dist/*.yml artifacts/ || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'artifacts/**'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
